[build]
command = "npm run build"
publish = "build"
  [build.environment]
    # cache Cypress binary in local "node_modules" folder
    # so Netlify caches it
    CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
    # set TERM variable for terminal output
    TERM = "xterm"

[[plugins]]
# runs Cypress tests against the deployed URL
package = "netlify-plugin-cypress"
  # Testing the built production version
  [plugins.inputs.postBuild]
    enable = true
    record = true
    group = '1: testing built site'

# Config reference examples: https://www.npmjs.com/package/netlify-plugin-cypress/v/1.9.1