[build]
  command = "next build"
  # publish directory is handled by the Next.js plugin, so you can omit it
  # publish = ".next"
  [build.environment]
    CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
    TERM = "xterm"

# Use the official Next.js Netlify plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Use the Cypress Netlify plugin
[[plugins]]
  package = "netlify-plugin-cypress"

  # Run Cypress tests *before* the build (optional)
  [plugins.inputs.preBuild]
    enable = true
    record = true
    group = "1: testing dev site"
    start = "npm run dev"
    wait-on = "http://localhost:3000"
    wait-on-timeout = 30

  # Run Cypress tests *after* the site is deployed (optional)
  [plugins.inputs.postBuild]
    enable = false
