[build]
  command = "next build"
  [build.environment]
    # cache Cypress binary in local "node_modules" folder
    # so Netlify caches it
    CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
    # set TERM variable for terminal output
    TERM = "xterm"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-cypress"

  # do not run tests after deploy (testing)
  [plugins.inputs]
    enable = false

  # run tests postBuild
  [plugins.inputs.postBuild]
    enable = true
    start = "npm run start"
    wait-on = "http://localhost:3000"
    wait-on-timeout = "30" # seconds

# Optional: cache static chunks for better performance
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Optional: image optimization redirects
[[redirects]]
  from = "/_next/image"
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
  status = 200
  query = { url = ":url", w = ":width", q = ":quality" }

[[redirects]]
  from = "/_ipx/*"
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
  status = 200
  query = { url = ":url", w = ":width", q = ":quality" }
